[package]
name = "quickcheck_macros"
version = "0.2.14"  #:version
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A macro attribute for quickcheck."
documentation = "http://burntsushi.net/rustdoc/quickcheck/"
homepage = "https://github.com/BurntSushi/quickcheck"
repository = "https://github.com/BurntSushi/quickcheck"
readme = "../README.md"
keywords = ["testing", "quickcheck", "property", "shrinking", "fuzz"]
license = "Unlicense/MIT"

[lib]
name = "quickcheck_macros"
path = "src/lib.rs"
plugin = true

[[test]]
name = "attribute"
path = "examples/attribute.rs"

[dependencies.quickcheck]
path = ".."
version = "*"
